import { Inter } from "next/font/google";
import Navbar from "../components/Navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App Nueva cosa",
  description: "Generated by create por mi ",
};

 function ApodLayout({ children }) {
  return (
      <body className={inter.className}>
      <Navbar/>
      {children}
      </body>
  );
}

export default ApodLayout;